services:
  - type: worker
    name: discord-product-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python trend_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

